<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
$this->setFrameMode(true);
$strSectionEdit = CIBlock::GetArrayByID($arParams["IBLOCK_ID"], "SECTION_EDIT");
$strSectionDelete = CIBlock::GetArrayByID($arParams["IBLOCK_ID"], "SECTION_DELETE");
$arSectionDeleteParams = array("CONFIRM" => GetMessage('CT_BCSL_ELEMENT_DELETE_CONFIRM'));
?>
<?
// pr($arParams);
// pr($arResult);
?>

	<?foreach ($arResult['SECTIONS'] as &$arSection):?>
		<?$this->AddEditAction($arSection['ID'], $arSection['EDIT_LINK'], $strSectionEdit);
		$this->AddDeleteAction($arSection['ID'], $arSection['DELETE_LINK'], $strSectionDelete, $arSectionDeleteParams);?>
		<h2><?=$arSection['NAME']?></h2>

		<?//pr($arSection['ID']);?>
		
		<?$APPLICATION->IncludeComponent(
	    "bitrix:catalog.section", 
	    "base_26", 
	    array(
	        "ACTION_VARIABLE" => "action",
	        "ADD_PICT_PROP" => "MORE_PHOTO",
	        "ADD_PROPERTIES_TO_BASKET" => "Y",
	        "ADD_SECTIONS_CHAIN" => (isset($arParams["ADD_SECTIONS_CHAIN"]) ? $arParams["ADD_SECTIONS_CHAIN"] : ''),
	        "AJAX_MODE" => "N",
	        "AJAX_OPTION_ADDITIONAL" => "",
	        "AJAX_OPTION_HISTORY" => "N",
	        "AJAX_OPTION_JUMP" => "N",
	        "AJAX_OPTION_STYLE" => "N",
	        "BACKGROUND_IMAGE" => "-",
	        "BASKET_URL" => "/personal/cart/",
	        "BROWSER_TITLE" => "-",
	        "CACHE_FILTER" => "Y",
	        "CACHE_GROUPS" =>$arParams["CACHE_GROUPS"],
	        "CACHE_TIME" => $arParams["CACHE_TIME"],
	        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
	        "COMPARE_PATH" => "/catalog/compare/",
	        "COMPONENT_TEMPLATE" => "main_static",
	        "CONVERT_CURRENCY" => "Y",
	        "CURRENCY_ID" => "RUB",
	        "DETAIL_URL" => "/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
	        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
	        "DISCOUNT_PERCENT_POSITION" => "top-right",
	        "DISPLAY_BOTTOM_PAGER" => "N",
	        "ELEMENT_SORT_FIELD" => "timestamp_x",
	        "ELEMENT_SORT_FIELD2" => "sort",
	        "ELEMENT_SORT_ORDER" => "desc",
	        "ELEMENT_SORT_ORDER2" => "asc",
	        "HIDE_NOT_AVAILABLE" => "Y",
	        "IBLOCK_ID" =>  $arParams["IBLOCK_ID"],
	        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
	        "INCLUDE_SUBSECTIONS" => "Y",
	        "LABEL_PROP" => "NEWPRODUCT",
	        "LINE_ELEMENT_COUNT" => "3",
	        "MESSAGE_404" => "",
	        "MESS_BTN_ADD_TO_BASKET" => "Купить",
	        "MESS_BTN_BUY" => "Купить",
	        "MESS_BTN_DETAIL" => "Подробнее",
	        "MESS_BTN_SUBSCRIBE" => "Подписаться",
	        "MESS_NOT_AVAILABLE" => "Нет в наличии",
	        "META_DESCRIPTION" => "-",
	        "META_KEYWORDS" => "-",
	        "NOT_LAZY_COUNTER" => "3",
	        "OFFERS_CART_PROPERTIES" => array(
	            0 => "WEIGHT",
	            1 => "DOUGH",
	            2 => "QUANT",
	            3 => "NACHINKA",
	        ),
	        "OFFERS_FIELD_CODE" => array(
	            0 => "ID",
	            1 => "NAME",
	            2 => "PREVIEW_TEXT",
	            3 => "PREVIEW_PICTURE",
	            4 => "",
	        ),
	        "OFFERS_LIMIT" => "0",
	        "OFFERS_PROPERTY_CODE" => array(
	            0 => "WEIGHT",
	            1 => "DOUGH",
	            2 => "QUANT",
	            3 => "NACHINKA",
	            4 => "",
	        ),
	        "OFFERS_SORT_FIELD" => "sort",
	        "OFFERS_SORT_FIELD2" => "name",
	        "OFFERS_SORT_ORDER" => "asc",
	        "OFFERS_SORT_ORDER2" => "asc",
	        "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
	        "OFFER_TREE_PROPS" => array(
	            0 => "WEIGHT",
	            1 => "DOUGH",
	            2 => "NACHINKA",
	            3 => "QUANT",
	        ),
	        "PAGER_BASE_LINK_ENABLE" => "N",
	        "PAGER_DESC_NUMBERING" => "N",
	        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	        "PAGER_SHOW_ALL" => "N",
	        "PAGER_SHOW_ALWAYS" => "N",
	        "PAGER_TEMPLATE" => ".default",
	        "PAGER_TITLE" => "Товары",
	        "PAGE_ELEMENT_COUNT" => "8",
	        "PARTIAL_PRODUCT_PROPERTIES" => "Y",
	        "PRICE_CODE" => array(
	            0 => "BASE",
	        ),
	        "PRICE_VAT_INCLUDE" => "Y",
	        "PRODUCT_DISPLAY_MODE" => "Y",
	        "PRODUCT_ID_VARIABLE" => "id",
	        "PRODUCT_PROPERTIES" => "",
	        "PRODUCT_PROPS_VARIABLE" => "prop",
	        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
	        "PRODUCT_SUBSCRIPTION" => "Y",
	        "PROPERTY_CODE" => array(
	            1 => "ARTNUMBER",
	            2 => "PROTEINS",
	            3 => "FATS",
	            4 => "CARBOHYDRATES",
	            5 => "CALORIE",
	            6 => "CALORIES",
	            7 => "TASTE",
	            8 => "TYPES",
	            9 => "DOUGH",
	        ),
	        "SECTION_CODE" => "",
	        "SECTION_ID" => $arSection['ID'],
	        "SECTION_ID_VARIABLE" => "SECTION_ID",
	        "SECTION_URL" => $arParams["SECTION_URL"],
	        "SECTION_USER_FIELDS" => array(
	            0 => "",
	            1 => "",
	        ),
	        "SEF_MODE" => "N",
	        "SET_BROWSER_TITLE" => "N",
	        "SET_LAST_MODIFIED" => "N",
	        "SET_META_DESCRIPTION" => "N",
	        "SET_META_KEYWORDS" => "N",
	        "SET_STATUS_404" => "N",
	        "SET_TITLE" => "N",
	        "SHOW_404" => "N",
	        "SHOW_ALL_WO_SECTION" => "Y",
	        "SHOW_CLOSE_POPUP" => "Y",
	        "SHOW_DISCOUNT_PERCENT" => "Y",
	        "SHOW_OLD_PRICE" => "Y",
	        "SHOW_PRICE_COUNT" => "1",
	        "SLIDER_ID" => "new-products",
	        "TOP" => "Y",
	        "USE_MAIN_ELEMENT_SECTION" => "N",
	        "USE_PRICE_COUNT" => "N",
	        "USE_PRODUCT_QUANTITY" => "Y",
	        "DAY_WEEK" => $arParams["DAY_WEEK"],
	        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
	        "TEMPLATE_THEME" => "blue",
	        "SHOW_MAX_QUANTITY" => "N",
	        "RCM_TYPE" => "personal",
	        "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
	        "SHOW_FROM_SECTION" => "N",
	        "ADD_TO_BASKET_ACTION" => "ADD",
	        "MESS_BTN_COMPARE" => "Сравнить",
	        "COMPARE_NAME" => "CATALOG_COMPARE_LIST",
	        "USE_ENHANCED_ECOMMERCE" => "N",
	        "LAZY_LOAD" => "N",
	        "LOAD_ON_SCROLL" => "N",
	        "COMPATIBLE_MODE" => "Y",
	        "HIDE_BASKET"=>$arParams["HIDE_BASKET"],
	        "CUISINE"=>$arParams["CUISINE"],
	        "BUY_BUTTON"=>$arParams['BUY_BUTTON'],
			"USER_TYPE"=>$arParams['USER_TYPE']
	    ),
	    false
	);?>
	<?endforeach?>


